### ISSUE TITLE
startup error when port not specified

### ISSUE THREAD

**Issue by gucki** [ikai/jruby-memcache-client#2]
If you specify a server simply by it's ip without a port (1.2.3.4 and not 1.2.3.4:11211) startups fails like:

com.meetup.memcached.SockIOPool Sat May 01 13:39:04 CEST 2010 - ++++ failed to get SockIO obj for: 1.2.3.4
com.meetup.memcached.SockIOPool Sat May 01 13:39:04 CEST 2010 - 1
java.lang.ArrayIndexOutOfBoundsException: 1
    at com.meetup.memcached.SockIOPool$SockIO.<init>(SockIOPool.java:1583)
    at com.meetup.memcached.SockIOPool.createSocket(SockIOPool.java:780)
    at com.meetup.memcached.SockIOPool.populateBuckets(SockIOPool.java:669)

**Comment by fredjean** [comment]
Will look into it.

**Comment by fredjean** [comment]
Writing specs to attempt to reproduce.

**Comment by fredjean** [comment]
I just committed code that normalize the server address using the default port (11211) if the port isn't provided. I am waiting on the result of a discussion with a contributor before cutting a release.
